### PR TITLE
495 histogram accuracy

### LINKED ISSUE #495: Histograms - add accuracy measures
Note: There are two types of accuracy re: histograms

1. "universal" accuracy -- e.g. one accuracy measure for the entire histogram (**not yet available**)
2. accuracy for each cell/category (**available**)

This issue is to implement (2) ^ above.

### Basic flow

- Iterate through teach category and re-use the noise scale parameter.
- This changes the results.
  - Set the "global" accuracy value as None/null
  - For the results, include a measure of accuracy for each category in tuple and dict formats.
    - tuple format:  `[(category, accuracy), (category, accuracy), etc.]`
       - use the current category order, and include accuracy for "uncategorized"
    - dict format: `{category: accuracy, category: accuracy, etc.}`

### files to change
- [dp_histogram_categorical_spec.py](https://github.com/opendp/dpcreator/blob/develop/server/opendp_apps/analysis/tools/dp_histogram_categorical_spec.py)
- [dp_histogram_integer_spec.py](https://github.com/opendp/dpcreator/blob/develop/server/opendp_apps/analysis/tools/dp_histogram_integer_spec.py)

### PR DESCRIPTION
**Pull request by ecowan**
Closes #495

### CODE REVIEW

**Review by raprasad — CHANGES_REQUESTED** [review]
- ~~Delete the file `dp_histogram_spec.py` (and any related imports)~~
   - from stand-up ^, perhaps use as a base class to factor out common functionality
- Accuracy description for histograms
  - In dp_histogram_integer.py and dp_histogram_categorical.py:
    - Add the`get_accuracy_text` function to `set_accuracy`
       - See `dp_count_spec.py` to see where `set_accuracy` is used
       - Create a new template file for histogram accuracy to be sent to `set_accuracy`
- Accuracy description within the general description
     - (Possible solution...free free to discuss)
     - In `stat_spec.py`, for `get_release_dict` add arguments: `description_template_html` and `description_template_text` with defaults of `None`
        - If the value(s) is/are None, default to the current values in the function
        - Create new templates to reflect a histogram description -- with if/then statements if there are too many values to display

**Comment by ecowan** [comment]
> * ~Delete the file `dp_histogram_spec.py` (and any related imports)~
>       
>       * from stand-up ^, perhaps use as a base class to factor out common functionality
> 
>     * Accuracy description for histograms
>       
>       * In dp_histogram_integer.py and dp_histogram_categorical.py:
>         
>         * Add the`get_accuracy_text` function to `set_accuracy`
>           
>           * See `dp_count_spec.py` to see where `set_accuracy` is used
>           * Create a new template file for histogram accuracy to be sent to `set_accuracy`
> 
>     * Accuracy description within the general description
>       
>       * (Possible solution...free free to discuss)
>       * In `stat_spec.py`, for `get_release_dict` add arguments: `description_template_html` and `description_template_text` with defaults of `None`
>         
>         * If the value(s) is/are None, default to the current values in the function
>         * Create new templates to reflect a histogram description -- with if/then statements if there are too many values to display

@raprasad This already exists and is being used in the `set_accuracy` function at line 180 in dp_histogram_categorical_spec.py and 136 for integer histograms (see also server/opendp_apps/analysis/templates/analysis/dp_histogram_accuracy_default.html)

**Comment by raprasad** [comment]
@ecowan 
- I see the accuracy description for the histograms. Looks good. (I missed it.)
- The general description has an outdated accuracy description within it (2nd bullet). That one needs updating--it can use the accuracy description you already have. (see below)
   - Also, the general description for a histogram is close to unreadable with more than a few categories/values. 
      - Can it be written in a more general way with the assumption that the web page and PDF will have the chart for viewing (as well as a future table)
      - (If ambitious, you could try adding a `description.histogram_table` with a two-column text table (but probably easier to simply use the real data on the HTML page)
---

- `accuracy.message` is different from the last sentence in `description.html`/`description.text`

```json
{
"accuracy": {
                "value": 5.075173853046817,
                "message": "There is a probability of <b>95.0%</b> that a count in the  <b>DP Histogram</b> will\ndiffer from the count in the true Histogram by at most <b>5.075173853046817</b> units. Here the\nunits are the same units the variable <b>Trial</b> has in the dataset."
            },
"description": {
                "html": "A differentially private <b>Histogram</b> for variable <b>Trial</b> was calculated with the result <b>{&#x27;categories&#x27;: [0, 1, 2, 3, 4, 5, 6, 7, &#x27;uncategorized&#x27;], &#x27;values&#x27;: [61, 0, 0, 4, 112, 8, 1, 3, 0], &#x27;category_value_pairs&#x27;: [(0, 61), (1, 0), (2, 0), (3, 4), (4, 112), (5, 8), (6, 1), (7, 3), (&#x27;uncategorized&#x27;, 0)]}</b>.  There is a probability of <b>95.0%</b> that the <b>DP Histogram</b> will differ from\nthe true Histogram by at most <b>5.075173853046817</b> units. Here the units are the same units\nthe variable <b>Trial</b> has in the dataset.",
                "text": "A differentially private Histogram for variable \"Trial\" was calculated with the result {&#x27;categories&#x27;: [0, 1, 2, 3, 4, 5, 6, 7, &#x27;uncategorized&#x27;], &#x27;values&#x27;: [61, 0, 0, 4, 112, 8, 1, 3, 0], &#x27;category_value_pairs&#x27;: [(0, 61), (1, 0), (2, 0), (3, 4), (4, 112), (5, 8), (6, 1), (7, 3), (&#x27;uncategorized&#x27;, 0)]}. There is a probability of 95.0% that the DP Histogram will differ from the true Histogram by at most 5.075173853046817 units. Here the units are the same units the variable Trial has in the dataset."
            }
        }
```

**Review by ekraffmiller — APPROVED** [review]
This looks good - the description in the Release page text makes sense to me. (But I'm not sure if there changes in the text that still need to happen based on Raman's change request)

**Comment by ecowan** [comment]
Note from standup: we also need to round values in sentences (accuracy, etc.) to 2 significant digits.

**Review by raprasad — APPROVED** [review]

**Pull request merged**
