### PR TITLE
Migration script

### PR DESCRIPTION
**Pull request by ecowan**
Improving migrations

### CODE REVIEW

**Comment by mikephelan** [comment]
This breaks the Docker build for me. Prior to this test I verified that Docker was running via the code in the master branch.

From the README.md:
The first time you run (or anytime schema changes have been made) you need to run migrate manually:

docker-compose run server ./server/migrate.sh

`WARNING: Image for service server was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./server/migrate.sh\": stat ./server/migrate.sh: no such file or directory": unknown`

After running the above command, the docker-compose up command (I verified it was working prior to the run server command) is broken.

`server_1  | python: can't open file '/code/server/server/manage.py': [Errno 2] No such file or directory
opendp-ux_server_1 exited with code 2`

Running docker-compose up --build after this results in this error.
`server_1  | python: can't open file '/code/server/server/manage.py': [Errno 2] No such file or directory
opendp-ux_server_1 exited with code 2`

**Comment by ecowan** [comment]
Thanks, this was a good reminder to always do `docker-compose down` and rebuild everything to make sure it works from scratch and no local path configurations are masking problems. I've fixed the path issues and improved the readme.

**Comment by raprasad** [comment]
Am getting an error when trying to log in through the admin screen

```bash
server_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 215, in clean
server_1  |     self.user_cache = authenticate(self.request, username=username, password=password)
server_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
server_1  |     user = backend.authenticate(request, **credentials)
server_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/backends.py", line 42, in authenticate
server_1  |     user = UserModel._default_manager.get_by_natural_key(username)
server_1  | AttributeError: 'PolymorphicManager' object has no attribute 'get_by_natural_key'
```

**Review by raprasad — APPROVED** [review]
Approved

**Pull request merged**
